name: conexion_agraria
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.6
  page_view_indicators: ^2.0.0
  intl: ^0.17.0
  google_maps_flutter: ^2.2.2 # Asegúrate de tener también el paquete de Google Maps
  location: ^6.0.0 # Asegúrate de tener la versión correcta
  permission_handler: ^11.3.1  # Agrega esta línea
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  firebase_database: ^11.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icono2.png"  # Define la imagen que usará tanto para Android como para iOS
  adaptive_icon_background: "#000000"  # Fondo para el ícono adaptativo (solo en Android)
  adaptive_icon_foreground: "lib/assets/icono2.png"  # Imagen del ícono adaptativo (solo en Android)

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.png
    - lib/assets/icono_campecino-gris.png
    - lib/assets/icono2.png
    - lib/assets/icono_campecino2.webp
    - lib/assets/default_image.png
