// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSe_2lz8x6UVV5gcLGuLD0aguzc3voMqY',
    appId: '1:875677956740:web:a66b0f292ae7d70608a0d1',
    messagingSenderId: '875677956740',
    projectId: 'conexion-agraria',
    authDomain: 'conexion-agraria.firebaseapp.com',
    databaseURL: 'https://conexion-agraria-default-rtdb.firebaseio.com',
    storageBucket: 'conexion-agraria.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXXQDPVSLbcVimCzIuAIZOrOYqy5wS4n4',
    appId: '1:875677956740:android:046d0796484b51e208a0d1',
    messagingSenderId: '875677956740',
    projectId: 'conexion-agraria',
    databaseURL: 'https://conexion-agraria-default-rtdb.firebaseio.com',
    storageBucket: 'conexion-agraria.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLYChMNLAj-hWOkIdtQpqxwgVTFUBtpbE',
    appId: '1:875677956740:ios:ceec75e4a014ca8a08a0d1',
    messagingSenderId: '875677956740',
    projectId: 'conexion-agraria',
    databaseURL: 'https://conexion-agraria-default-rtdb.firebaseio.com',
    storageBucket: 'conexion-agraria.appspot.com',
    iosBundleId: 'com.example.conexionAgraria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLYChMNLAj-hWOkIdtQpqxwgVTFUBtpbE',
    appId: '1:875677956740:ios:ceec75e4a014ca8a08a0d1',
    messagingSenderId: '875677956740',
    projectId: 'conexion-agraria',
    databaseURL: 'https://conexion-agraria-default-rtdb.firebaseio.com',
    storageBucket: 'conexion-agraria.appspot.com',
    iosBundleId: 'com.example.conexionAgraria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1J68N9Y11axVHSxLEF4J_wJhYNzRuAsg',
    appId: '1:875677956740:web:3b8796f5181941e408a0d1',
    messagingSenderId: '875677956740',
    projectId: 'conexion-agraria',
    authDomain: 'conexion-agraria.firebaseapp.com',
    databaseURL: 'https://conexion-agraria-default-rtdb.firebaseio.com',
    storageBucket: 'conexion-agraria.appspot.com',
  );
}
